image: sikalabs/ci

stages:
  - build
  - deploy dev

variables:
  IMAGE_TAG: $CI_COMMIT_REF_SLUG

build:
  stage: build
  variables:
    COMPOSE_FILE: docker-compose.yml:docker-compose.mysql.yml
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose build
    - docker-compose push

.deploy: &deploy_template
  stage: deploy dev
  variables:
    COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    DOCKER_HOST: $DEV_DOCKER_HOST
    DOCKER_CERT_PATH: .ci-tmp/docker
    DOCKER_TLS_VERIFY: "1"
    HOST: $CI_COMMIT_REF_SLUG.$DEV_DOMAIN
  before_script:
    - mkdir -p $DOCKER_CERT_PATH
    - cp $DEV_DOCKER_CA_CERT $DOCKER_CERT_PATH/ca.pem
    - cp $DEV_DOCKER_CERT $DOCKER_CERT_PATH/cert.pem
    - cp $DEV_DOCKER_KEY $DOCKER_CERT_PATH/key.pem

deploy dev:
  <<: *deploy_template
  script:
    - make use-traefik-dev
    - docker-compose pull
    - docker-compose up -d --no-build
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.dev.qcm.sikademo.com
    on_stop: stop dev

stop dev:
  <<: *deploy_template
  when: manual
  script:
    - docker ps --filter label=com.docker.compose.project=$COMPOSE_PROJECT_NAME --format {{.ID}} | xargs -n 1 docker rm --force --volumes
    - docker system prune -f --all
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop
