version: "3.8"
services:
  hello-nginx:
    networks:
      - default
      - traefik
    labels:
      - traefik.frontend.rule=Host:${HOST?}
      - traefik.enable=true
      - qcm-client=foo
      - qcm-support=l3

networks:
  traefik:
    external:
      name: traefik
