version: "3.8"
services:
  phpinfo:
    volumes:
      - ./src/phpinfo:/app
  phpinfo-nginx:
    volumes:
      - ./src/phpinfo:/app
    ports:
      - ${PORT_PHPINFO:-8000}:80
  hello:
    volumes:
      - ./src/hello:/app
  hello-nginx:
    volumes:
      - ./src/hello:/app
    ports:
      - ${PORT_HELLO:-8001}:80
