filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"


processors:
  - decode_json_fields:
      fields:
                  - message
      process_array: false
      max_depth: 1
      target: "xxx"
      overwrite_keys: false
      add_error_key: true

output.elasticsearch:
  hosts:
    - "elk-qcm.sikademo.com:9200"
