global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs: []

rule_files:
  - prometheus.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
