global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - dev.qcm.sikademo.com:8081
          - prod.qcm.sikademo.com:8081
  - job_name: traefik
    static_configs:
      - targets:
          - dev.qcm.sikademo.com:8080
          - prod.qcm.sikademo.com:8080

rule_files:
  - prometheus.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
